### ISSUE TITLE
lost of error suddently apear

### ISSUE THREAD

**Issue by ppllpig** [ngc7331/docker-derper#2]
rejected: failed to query local tailscaled status: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: connection refused

works well before version auto updated,tailscale version must be same with docker-derper in docker?

**Comment by ngc7331** [comment]
This issue is closed, is the problem solved?

In some cases, the tailscale API may have changed, so it is recommended to keep the versions of the tailscale and derp containers the same. However, this should not be the case with the recent update (1.66.4 -> 1.68.0).

This error:
> Error: dial unix /var/run/tailscale/tailscaled.sock: connect: connection refused

looks like `tailscaled.sock` is not properly mounted into the container. It could be caused by a wrong startup parameter, or by not restarting the container after restarting tailscaled on host (which recreates the `tailscaled.sock` socket, and fails the mountpoint).
